In [1]:
import numpy as np

# creating array range 0 to 11


In [12]:
arr = np.arange(0, 11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# array index of 8

In [5]:
arr[8]

8

# get by range 1 to 5

In [6]:
arr[1:5]

array([1, 2, 3, 4])

In [7]:
arr[0:5]

array([0, 1, 2, 3, 4])

# set value for range


In [15]:
arr[0:5] = 100

In [16]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [17]:
#
slice_of_arr = arr[0:5]

In [18]:
slice_of_arr

array([100, 100, 100, 100, 100])

# Index 2D array

In [20]:
arr2d = np.array(((1, 2 ,3), (4, 5, 6), (19, 30, 20)))
arr2d

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [19, 30, 20]])

# Row index

In [21]:
arr2d[0]

array([1, 2, 3])

In [22]:
arr2d[0][0]

1

 # 2D Slice

In [24]:
arr2d

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [19, 30, 20]])

In [27]:
arr2d[:3,1:]

array([[ 2,  3],
       [ 5,  6],
       [30, 20]])

# Fancy Index

In [30]:
# we can put index value in any order
arr2d[[2,1]]

array([[19, 30, 20],
       [ 4,  5,  6]])